export const ActionType = {
  LOGIN_REQUEST_PENDING: 'LOGIN_REQUEST_PENDING',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED',

  SET_USER_STATE: 'SET_USER_STATE',

  GET_ORDERS_REQUEST_PENDING: 'GET_ORDERS_REQUEST_PENDING',
  GET_ORDERS_REQUEST_SUCCESS: 'GET_ORDERS_REQUEST_SUCCESS',
  GET_ORDERS_REQUEST_FAILED: 'GET_ORDERS_REQUEST_FAILED',

  GET_ORDER_REQUEST_PENDING: 'GET_ORDER_REQUEST_PENDING',
  GET_ORDER_REQUEST_SUCCESS: 'GET_ORDER_REQUEST_SUCCESS',
  GET_ORDER_REQUEST_FAILED: 'GET_ORDER_REQUEST_FAILED',

  UPDATE_ORDER_REQUEST_PENDING: 'UPDATE_ORDER_REQUEST_PENDING',
  UPDATE_ORDER_REQUEST_SUCCESS: 'UPDATE_ORDER_REQUEST_SUCCESS',
  UPDATE_ORDER_REQUEST_FAILED: 'UPDATE_ORDER_REQUEST_FAILED',
};
